[package]
name = "sofia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
serde_json = "1.0.59"
serde = { version = "1.0.136", features = ["derive"] }
